version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DOPPLER_TOKEN=${DOPPLER_BACKEND_TOKEN} # Inject token from environment
    command: doppler run -- java -jar target/prime-wraps-0.0.1-SNAPSHOT.jar
    restart: always

  frontend:
    build:
      context: ./frontend
      secrets:
        - DOPPLER_TOKEN
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: always
