services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DOPPLER_TOKEN=${DOPPLER_BACKEND_TOKEN}
    command: doppler run --config prd -- java -jar app.jar
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        - DOPPLER_TOKEN=${DOPPLER_FRONTEND_TOKEN}
    ports:
      - "8081:80"
    environment:
      - NODE_ENV=production
    restart: always
