secrets:
  doppler_frontend_token:
    environment: DOPPLER_TOKEN # This maps the host env var DOPPLER_TOKEN to a secret named doppler_frontend_token

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DOPPLER_TOKEN=${DOPPLER_BACKEND_TOKEN} # Inject token from environment
    command: doppler run -- java -jar target/prime-wraps-0.0.1-SNAPSHOT.jar
    restart: always

  frontend:
    build:
      context: ./frontend
      secrets:
        - doppler_frontend_token # Reference the top-level secret here
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: always
