spring:
  application:
    name: prime-wraps-backend
  
  # Database Configuration for Supabase PostgreSQL
  datasource:
    url: ${DB_URL}
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
  
  # Mail Configuration
  mail:
    host: smtp.mail.me.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    recipient: ${MAIL_RECIPIENT}

# Server Configuration
server:
  port: ${PORT:8080}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 24 hours

# CORS Configuration for production
cors:
  allowed-origins: ${FRONTEND_URL}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"

# Logging
logging:
  level:
    com.primewraps: INFO
    org.springframework.security: INFO 

# H2 Console (disabled for production)
  h2:
    console:
      enabled: false 